import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={`antialiased`}>
          <div className="w-[100%] flex justify-center">
            <div className="h-[30px] bg-white w-[100%] max-w-[1024px] px-[30px] flex justify-start gap-[20px]">
            <Link href={'/'}>Home</Link>
              <Link href={'/about'}>About</Link>
              <Link href={'/blogs'}>Blogs</Link>
              <Link href={'/contacts'}>Contacts</Link>
            </div>
          </div>
          {children}
        </body>
      </html>
  );
}
